import type { TemplateContext } from "../../types.js";

export function architectureMd(_ctx: TemplateContext): string {
  return `# Architecture Overview

> Auto-generated by harness init. Fill in or replace with sub-agent analysis output.

## System Overview

<!-- Describe the high-level architecture: major components, data flow, deployment model. -->

## Key Components

<!-- List the major modules/services and their responsibilities. -->

## Data Flow

<!-- Describe how data moves through the system. -->

## Constraints & Trade-offs

<!-- Non-obvious architectural decisions and their rationale. -->
`;
}
